package net.rf43.royaleapikit.consumer

import com.google.gson.annotations.SerializedName

object RawConstantsModel {
    data class RawConstant(
        @SerializedName("alliance_badges") val allianceBadges: List<RawConstantAllianceBadge>? = null,
        @SerializedName("arenas") val arenas: List<RawConstantArena>? = null,
        @SerializedName("cards") val cards: List<RawConstantCard>? = null,
        @SerializedName("cards_stats") val cardsStats: RawConstantCardsStats? = null
    )

    data class RawConstantAllianceBadge(
        @SerializedName("name") val name: String? = null,
        @SerializedName("category") val category: String? = null,
        @SerializedName("id") val id: Int? = null
    )

    data class RawConstantArena(
        @SerializedName("name") val name: String? = null,
        @SerializedName("arena") val arena: Int? = null,
        @SerializedName("chest_arena") val chestArena: String? = null,
        @SerializedName("tv_arena") val tvArena: String? = null,
        @SerializedName("is_in_use") val isInUse: Boolean? = null,
        @SerializedName("training_camp") val trainingCamp: Boolean? = null,
        @SerializedName("trophy_limit") val trophyLimit: Int? = null,
        @SerializedName("demote_trophy_limit") val demoteTrophyLimit: Int? = null,
        @SerializedName("chest_reward_multiplier") val chestRewardMultiplier: Int? = null,
        @SerializedName("shop_chest_reward_multiplier") val shopChestRewardMultiplier: Int? = null,
        @SerializedName("request_size") val requestSize: Int? = null,
        @SerializedName("max_donation_count_common") val maxDonationCountCommon: Int? = null,
        @SerializedName("max_donation_count_rare") val maxDonationCountRare: Int? = null,
        @SerializedName("max_donation_count_epic") val maxDonationCountEpic: Int? = null,
        @SerializedName("matchmaking_min_trophy_delta") val matchmakingMinTrophyDelta: Int? = null,
        @SerializedName("matchmaking_max_trophy_delta") val matchmakingMaxTrophyDelta: Int? = null,
        @SerializedName("matchmaking_max_seconds") val matchmakingMaxSeconds: Int? = null,
        @SerializedName("daily_donation_capacity_limit") val dailyDonationCapacityLimit: Int? = null,
        @SerializedName("battle_reward_gold") val battleRewardGold: Int? = null,
        @SerializedName("season_reward_chest") val seasonRewardChest: Any? = null,
        @SerializedName("quest_cycle") val questCycle: String? = null,
        @SerializedName("key") val key: String? = null,
        @SerializedName("title") val title: String? = null,
        @SerializedName("subtitle") val subtitle: String? = null,
        @SerializedName("arena_id") val arenaId: Int? = null,
        @SerializedName("league_id") val leagueId: String? = null,
        @SerializedName("id") val id: Int? = null
    )

    data class RawConstantCard(
        @SerializedName("key") val key: String? = null,
        @SerializedName("name") val name: String? = null,
        @SerializedName("elixir") val elixir: Int? = null,
        @SerializedName("type") val type: String? = null,
        @SerializedName("rarity") val rarity: String? = null,
        @SerializedName("arena") val arena: Int? = null,
        @SerializedName("description") val description: String? = null,
        @SerializedName("id") val id: Int? = null
    )

    data class RawConstantCardsStats(
        @SerializedName("troop") val troops: List<RawConstantCardsStatsTroop>? = null,
        @SerializedName("building") val building: List<RawConstantCardsStatsBuilding>? = null,
        @SerializedName("spell") val spell: List<RawConstantCardsStatsSpell>? = null,
        @SerializedName("projectile") val projectile: List<RawConstantCardsStatsProjectile>? = null
    )

    data class RawConstantCardsStatsTroop(
        @SerializedName("name") val name: String? = null,
        @SerializedName("rarity") val rarity: String? = null,
        @SerializedName("sight_range") val sight_range: Int? = null,
        @SerializedName("deploy_time") val deploy_time: Int? = null,
        @SerializedName("speed") val speed: Int? = null,
        @SerializedName("hitpoints") val hitpoints: Int? = null,
        @SerializedName("hit_speed") val hit_speed: Int? = null,
        @SerializedName("load_time") val load_time: Int? = null,
        @SerializedName("damage") val damage: Int? = null,
        @SerializedName("load_first_hit") val load_first_hit: Boolean? = null,
        @SerializedName("load_after_retarget") val load_after_retarget: Boolean? = null,
        @SerializedName("all_targets_hit") val all_targets_hit: Boolean? = null,
        @SerializedName("range") val range: Int? = null,
        @SerializedName("attacks_ground") val attacks_ground: Boolean? = null,
        @SerializedName("attacks_air") val attacks_air: Boolean? = null,
        @SerializedName("target_only_buildings") val target_only_buildings: Boolean? = null,
        @SerializedName("target_only_troops") val target_only_troops: Boolean? = null,
        @SerializedName("prestige_swf") val prestige_swf: String? = null,
        @SerializedName("prestige_export_name2") val prestige_export_name2: String? = null,
        @SerializedName("spawn_effect_once") val spawn_effect_once: Boolean? = null,
        @SerializedName("crowd_effects") val crowd_effects: Boolean? = null,
        @SerializedName("ignore_pushback") val ignore_pushback: Boolean? = null,
        @SerializedName("scale") val scale: Int? = null,
        @SerializedName("collision_radius") val collision_radius: Int? = null,
        @SerializedName("mass") val mass: Int? = null,
        @SerializedName("show_health_number") val show_health_number: Boolean? = null,
        @SerializedName("fly_direct_paths") val fly_direct_paths: Boolean? = null,
        @SerializedName("fly_from_ground") val fly_from_ground: Boolean? = null,
        @SerializedName("heal_on_morph") val heal_on_morph: Boolean? = null,
        @SerializedName("morph_keep_target") val morph_keep_target: Boolean? = null,
        @SerializedName("dash_only_once") val dash_only_once: Boolean? = null,
        @SerializedName("destroy_at_limit") val destroy_at_limit: Boolean? = null,
        @SerializedName("spawn_attach") val spawn_attach: Boolean? = null,
        @SerializedName("death_spawn_pushback") val death_spawn_pushback: Boolean? = null,
        @SerializedName("death_inherit_ignore_list") val death_inherit_ignore_list: Boolean? = null,
        @SerializedName("kamikaze") val kamikaze: Boolean? = null,
        @SerializedName("projectile_start_radius") val projectile_start_radius: Int? = null,
        @SerializedName("projectile_start_z") val projectile_start_z: Int? = null,
        @SerializedName("dont_stop_move_anim") val dont_stop_move_anim: Boolean? = null,
        @SerializedName("is_summoner_tower") val is_summoner_tower: Boolean? = null,
        @SerializedName("self_as_aoe_center") val self_as_aoe_center: Boolean? = null,
        @SerializedName("hides_when_not_attacking") val hides_when_not_attacking: Boolean? = null,
        @SerializedName("hide_before_first_hit") val hide_before_first_hit: Boolean? = null,
        @SerializedName("special_attack_when_hidden") val special_attack_when_hidden: Boolean? = null,
        @SerializedName("has_rotation_on_timeline") val has_rotation_on_timeline: Boolean? = null,
        @SerializedName("jump_enabled") val jump_enabled: Boolean? = null,
        @SerializedName("retarget_after_attack") val retarget_after_attack: Boolean? = null,
        @SerializedName("burst_keep_target") val burst_keep_target: Boolean? = null,
        @SerializedName("burst_affect_animation") val burst_affect_animation: Boolean? = null,
        @SerializedName("building_target") val building_target: Boolean? = null,
        @SerializedName("spawn_const_priority") val spawn_const_priority: Boolean? = null,
        @SerializedName("deprioritize_targets_with_buff") val deprioritize_targets_with_buff: Boolean? = null,
        @SerializedName("override_attack_finish_time") val override_attack_finish_time: Boolean? = null,
        @SerializedName("name_en") val name_en: String? = null,
        @SerializedName("key") val key: String? = null,
        @SerializedName("elixir") val elixir: Int? = null,
        @SerializedName("type") val type: String? = null,
        @SerializedName("arena") val arena: Int? = null,
        @SerializedName("description") val description: String? = null,
        @SerializedName("id") val id: Int? = null,
        @SerializedName("summon_character") val summon_character: String? = null,
        @SerializedName("summon_number") val summon_number: Int? = null,
        @SerializedName("speed_en") val speed_en: String? = null,
        @SerializedName("dps") val dps: Double? = null,
        @SerializedName("hitpoints_per_level") val hitpointsPerLevel: List<Int>? = null,
        @SerializedName("damage_per_level") val damagePerLevel: List<Int>? = null,
        @SerializedName("dps_per_level") val dpsPerLevel: List<Int>? = null
    )

    data class RawConstantCardsStatsBuilding(
        @SerializedName("name") val name: String? = null,
        @SerializedName("rarity") val rarity: String? = null,
        @SerializedName("sight_range") val sight_range: Int? = null,
        @SerializedName("hitpoints") val hitpoints: Int? = null,
        @SerializedName("hit_speed") val hit_speed: Int? = null,
        @SerializedName("load_time") val load_time: Int? = null,
        @SerializedName("load_first_hit") val load_first_hit: Boolean? = null,
        @SerializedName("load_after_retarget") val load_after_retarget: Boolean? = null,
        @SerializedName("projectile") val projectile: String? = null,
        @SerializedName("all_targets_hit") val all_targets_hit: Boolean? = null,
        @SerializedName("range") val range: Int? = null,
        @SerializedName("attacks_ground") val attacks_ground: Boolean? = null,
        @SerializedName("attacks_air") val attacks_air: Boolean? = null,
        @SerializedName("target_only_buildings") val target_only_buildings: Boolean? = null,
        @SerializedName("target_only_troops") val target_only_troops: Boolean? = null,
        @SerializedName("prestige_swf") val prestige_swf: String? = null,
        @SerializedName("attached_character_height") val attached_character_height: Int? = null,
        @SerializedName("spawn_effect_once") val spawn_effect_once: Boolean? = null,
        @SerializedName("crowd_effects") val crowd_effects: Boolean? = null,
        @SerializedName("ignore_pushback") val ignore_pushback: Boolean? = null,
        @SerializedName("scale") val scale: Int? = null,
        @SerializedName("collision_radius") val collision_radius: Int? = null,
        @SerializedName("tile_size_override") val tile_size_override: Int? = null,
        @SerializedName("show_health_number") val show_health_number: Boolean? = null,
        @SerializedName("fly_direct_paths") val fly_direct_paths: Boolean? = null,
        @SerializedName("fly_from_ground") val fly_from_ground: Boolean? = null,
        @SerializedName("heal_on_morph") val heal_on_morph: Boolean? = null,
        @SerializedName("morph_keep_target") val morph_keep_target: Boolean? = null,
        @SerializedName("dash_only_once") val dash_only_once: Boolean? = null,
        @SerializedName("destroy_at_limit") val destroy_at_limit: Boolean? = null,
        @SerializedName("spawn_attach") val spawn_attach: Boolean? = null,
        @SerializedName("death_spawn_pushback") val death_spawn_pushback: Boolean? = null,
        @SerializedName("death_inherit_ignore_list") val death_inherit_ignore_list: Boolean? = null,
        @SerializedName("kamikaze") val kamikaze: Boolean? = null,
        @SerializedName("projectile_start_radius") val projectile_start_radius: Int? = null,
        @SerializedName("projectile_start_z") val projectile_start_z: Int? = null,
        @SerializedName("dont_stop_move_anim") val dont_stop_move_anim: Boolean? = null,
        @SerializedName("is_summoner_tower") val is_summoner_tower: Boolean? = null,
        @SerializedName("no_deploy_size_w") val no_deploy_size_w: Int? = null,
        @SerializedName("no_deploy_size_h") val no_deploy_size_h: Int? = null,
        @SerializedName("self_as_aoe_center") val self_as_aoe_center: Boolean? = null,
        @SerializedName("hides_when_not_attacking") val hides_when_not_attacking: Boolean? = null,
        @SerializedName("hide_before_first_hit") val hide_before_first_hit: Boolean? = null,
        @SerializedName("special_attack_when_hidden") val special_attack_when_hidden: Boolean? = null,
        @SerializedName("has_rotation_on_timeline") val has_rotation_on_timeline: Boolean? = null,
        @SerializedName("turret_movement") val turret_movement: Int? = null,
        @SerializedName("projectile_y_offset") val projectile_y_offset: Int? = null,
        @SerializedName("jump_enabled") val jump_enabled: Boolean? = null,
        @SerializedName("retarget_after_attack") val retarget_after_attack: Boolean? = null,
        @SerializedName("burst_keep_target") val burst_keep_target: Boolean? = null,
        @SerializedName("burst_affect_animation") val burst_affect_animation: Boolean? = null,
        @SerializedName("building_target") val building_target: Boolean? = null,
        @SerializedName("spawn_const_priority") val spawn_const_priority: Boolean? = null,
        @SerializedName("deprioritize_targets_with_buff") val deprioritize_targets_with_buff: Boolean? = null,
        @SerializedName("override_attack_finish_time") val override_attack_finish_time: Boolean? = null,
        @SerializedName("name_en") val name_en: String? = null,
        @SerializedName("hitpoints_per_level") val hitpoints_per_level: List<Int>? = null,
        @SerializedName("damage_per_level") val damage_per_level: List<Int>? = null,
        @SerializedName("dps_per_level") val dps_per_level: List<Int>? = null
    )

    data class RawConstantCardsStatsSpell(
        @SerializedName("name") val name: String? = null,
        @SerializedName("rarity") val rarity: String? = null,
        @SerializedName("life_duration") val life_duration: Int? = null,
        @SerializedName("life_duration_increase_per_level") val life_duration_increase_per_level: Int? = null,
        @SerializedName("life_duration_increase_after_tournament_cap") val life_duration_increase_after_tournament_cap: Int? = null,
        @SerializedName("affects_hidden") val affects_hidden: Boolean? = null,
        @SerializedName("radius") val radius: Int? = null,
        @SerializedName("hit_speed") val hit_speed: Int? = null,
        @SerializedName("damage") val damage: Int? = null,
        @SerializedName("no_effect_to_crown_towers") val no_effect_to_crown_towers: Boolean? = null,
        @SerializedName("crown_tower_damage_percent") val crown_tower_damage_percent: Int? = null,
        @SerializedName("hit_biggest_targets") val hit_biggest_targets: Boolean? = null,
        @SerializedName("buff") val buff: String? = null,
        @SerializedName("buff_time") val buff_time: Int? = null,
        @SerializedName("buff_time_increase_per_level") val buff_time_increase_per_level: Int? = null,
        @SerializedName("buff_time_increase_after_tournament_cap") val buff_time_increase_after_tournament_cap: Int? = null,
        @SerializedName("cap_buff_time_to_area_effect_time") val cap_buff_time_to_area_effect_time: Boolean? = null,
        @SerializedName("buff_number") val buff_number: Int? = null,
        @SerializedName("only_enemies") val only_enemies: Boolean? = null,
        @SerializedName("only_own_troops") val only_own_troops: Boolean? = null,
        @SerializedName("ignore_buildings") val ignore_buildings: Boolean? = null,
        @SerializedName("ignore_hero") val ignore_hero: Boolean? = null,
        @SerializedName("projectile") val projectile: Any? = null,
        @SerializedName("spawn_character") val spawn_character: Any? = null,
        @SerializedName("spawn_interval") val spawn_interval: Int? = null,
        @SerializedName("spawn_randomize_sequence") val spawn_randomize_sequence: Boolean? = null,
        @SerializedName("spawn_deploy_base_anim") val spawn_deploy_base_anim: Any? = null,
        @SerializedName("spawn_time") val spawn_time: Int? = null,
        @SerializedName("spawn_character_level_index") val spawn_character_level_index: Int? = null,
        @SerializedName("spawn_initial_delay") val spawn_initial_delay: Int? = null,
        @SerializedName("spawn_max_count") val spawn_max_count: Int? = null,
        @SerializedName("spawn_max_radius") val spawn_max_radius: Int? = null,
        @SerializedName("spawn_min_radius") val spawn_min_radius: Int? = null,
        @SerializedName("spawn_from_min_to_max") val spawn_from_min_to_max: Boolean? = null,
        @SerializedName("spawn_angle_shift") val spawn_angle_shift: Int? = null,
        @SerializedName("hits_ground") val hits_ground: Boolean? = null,
        @SerializedName("hits_air") val hits_air: Boolean? = null,
        @SerializedName("key") val key: String? = null,
        @SerializedName("elixir") val elixir: Int? = null,
        @SerializedName("type") val type: String? = null,
        @SerializedName("arena") val arena: Int? = null,
        @SerializedName("description") val description: String? = null,
        @SerializedName("id") val id: Int? = null,
        @SerializedName("hitpoints_per_level") val hitpoints_per_level: List<Int>? = null,
        @SerializedName("damage_per_level") val damage_per_level: List<Int>? = null,
        @SerializedName("dps_per_level") val dps_per_level: List<Int>? = null
    )

    data class RawConstantCardsStatsProjectile(
        @SerializedName("name") val name: String? = null,
        @SerializedName("rarity") val rarity: String? = null,
        @SerializedName("speed") val speed: Int? = null,
        @SerializedName("homing") val homing: Boolean? = null,
        @SerializedName("hit_effect_at_projectile") val hit_effect_at_projectile: Boolean? = null,
        @SerializedName("damage") val damage: Int? = null,
        @SerializedName("crown_tower_damage_percent") val crown_tower_damage_percent: Int? = null,
        @SerializedName("radius") val radius: Int? = null,
        @SerializedName("aoe_to_air") val aoe_to_air: Boolean? = null,
        @SerializedName("aoe_to_ground") val aoe_to_ground: Boolean? = null,
        @SerializedName("only_enemies") val only_enemies: Boolean? = null,
        @SerializedName("only_own_troops") val only_own_troops: Boolean? = null,
        @SerializedName("gravity") val gravity: Int? = null,
        @SerializedName("spawn_const_priority") val spawn_const_priority: Boolean? = null,
        @SerializedName("use360_frames") val use360_frames: Boolean? = null,
        @SerializedName("height_from_target_radius") val height_from_target_radius: Boolean? = null,
        @SerializedName("target_to_edge") val target_to_edge: Boolean? = null,
        @SerializedName("shakes_targets") val shakes_targets: Boolean? = null,
        @SerializedName("check_collisions") val check_collisions: Boolean? = null,
        @SerializedName("damage_per_level") val damage_per_level: List<Int>? = null,
        @SerializedName("dps") val dps: Int? = null,
        @SerializedName("dps_per_level") val dps_per_level: List<Int>? = null
    )
}